In [8]:
import numpy as np

X_stat = np.array([ [ 1, 2, 3], [ 4, -5, 6] ])
print("mean = ", X_stat.mean())
print("Variance = ", X_stat.var())
print("Standard Deviation = ", X_stat.std())
print("min = ", X_stat.min())
print("max = ", X_stat.max())
print("sum = ", X_stat.sum())
print("product = ", X_stat.prod())

mean =  1.8333333333333333
Variance =  11.805555555555557
Standard Deviation =  3.435921354681384
min =  -5
max =  6
sum =  11
product =  -720


In [21]:
import numpy as np

Z = np.arange(18).reshape((2,3,3))
print(Z)
print(Z.sum(axis=2))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[ 3 12 21]
 [30 39 48]]


In [29]:
import numpy as np

N = np.arange(6).reshape((3,2))
print(N)
print("Transpose = ", N.T)

[[0 1]
 [2 3]
 [4 5]]
Transpose =  [[0 2 4]
 [1 3 5]]


In [47]:
import numpy as np

X_broad = np.ones((3,3))
print(X_broad)
Y_broad = np.arange(3)
print(Y_broad)
Z_broad = X_broad + Y_broad
print(Z_broad)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [98]:
import numpy as np

# matrix addition
a_arr = np.array([60,70,80,90])
b_arr = np.arange(4)
c_arr = a_arr + b_arr
print(c_arr)

# matrix subtraction
d_arr = np.array([60,70,80,90])
e_arr = np.arange(4)
f_arr = d_arr - e_arr
print(f_arr)

# element-wise multiplication
A_arr = np.array([ [ 5,9], [4, 7] ])
B_arr = np.array( [ [2, 8], [1, 6] ] )
M_arr = A_arr * B_arr
print(M_arr)

# dot product/matrix multiplication
C_arr = np.array([ [ 5,9], [4, 7] ])
D_arr = np.array( [ [2, 8], [1, 6] ] )
#P_arr = np.dot(C_arr,D_arr)
P_arr = C_arr @ D_arr
print(P_arr)

R_div = np.array([ [ 25,65], [40, 14] ])
S_div = np.array([ [2, 10], [4, 5] ] )
T_div = R_div / S_div
print(T_div)

R_int_div = np.array([ [ 25,65], [40, 70] ])
S_int_div = np.array([ [2, 10], [8, 3] ] )
T_int_div = R_int_div // S_int_div
print(T_int_div)

R_mod = np.array([ [ 20,65], [40, 70] ])
S_mod = np.array([ [2, 10], [8, 3] ] )
T_mod = R_mod % S_mod
print(T_mod)

R_exp = np.array([ [ 4, 2], [3, 4 ] ] )
S_exp = np.array( [ [2, 10], [4, 5] ] )
T_exp = R_exp ** S_exp
print(T_exp)




[60 71 82 93]
[60 69 78 87]
[[10 72]
 [ 4 42]]
[[19 94]
 [15 74]]
[[12.5  6.5]
 [10.   2.8]]
[[12  6]
 [ 5 23]]
[[0 5]
 [0 1]]
[[  16 1024]
 [  81 1024]]


In [107]:
U = np.array([ [ 22, 45], [90, 4 ] ] )
print(U[U<45])

[22  4]


In [78]:
import numpy as np

tup_dim = (3, 4)
my_zeros_array = np.zeros(tup_dim, dtype = np.int16) 
print(my_zeros_array)

my_ones_array = np.ones(tup_dim, dtype = np.int16)
print(my_ones_array)

my_seven_array = np.full(tup_dim, 7, dtype=np.int16)
print(my_seven_array)

my_identity_array = np.identity(4, dtype=np.float64)
print(my_identity_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
import numpy as np

my_rand_array = np.random.rand(3,4)
print(my_rand_array)

tup_dim = (3, 4)
my_uninitialized_array = np.empty(tup_dim)
print(my_uninitialized_array)

[[0.366217   0.73325842 0.92657972 0.12350016]
 [0.35660453 0.45353409 0.2090999  0.08553308]
 [0.71238532 0.90114762 0.26976729 0.18374379]]
[[0.366217   0.73325842 0.92657972 0.12350016]
 [0.35660453 0.45353409 0.2090999  0.08553308]
 [0.71238532 0.90114762 0.26976729 0.18374379]]


In [15]:
import numpy as np
my_range_array = np.arange(10,30,5)
print(my_range_array)

my_spaced_array = np.linspace(1, 5/3, 6)
print(my_spaced_array)

[10 15 20 25]
[1.         1.13333333 1.26666667 1.4        1.53333333 1.66666667]


In [30]:
array_A = np.array([ [3,4,6], [0,8,1] ])
print(array_A.ndim)
print(array_A.shape)
print(array_A.size)
print(array_A.dtype)
print(array_A.itemsize)

2
(2, 3)
6
int64
8


In [60]:
import numpy as np
my_array = np.array([ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ])

print(my_array.ndim)
print(my_array.shape)
print(my_array.dtype)
print(my_array.size)

2
(3, 4)
int64
12


In [4]:
import numpy as np
import os
import pandas as pd

HOUSING_PATH = '/cxldata/datasets/project/housing'
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
my_df = housing_raw.iloc[:5]
my_df.to_csv('housing_short.csv', index=False)

File = housing_short.csv

def load_housing_data(file = FILE ):
    return np.loadtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skiprows=1, unpack=True)

longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr = load_housing_data()

NameError: name 'housing_short' is not defined

In [14]:
import numpy as np
import os

import pandas as pd
# defining housing.csv file path
HOUSING_PATH =  '/cxldata/datasets/project/housing'
# reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
# extracting only a few rows (5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]
# creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)

FILE = 'housing_short.csv'

def load_housing_data(file = FILE ):
    return np.loadtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skiprows=1, unpack=True)


longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr = load_housing_data()

print(median_house_value_arr)

[452600. 358500. 352100. 341300. 342200.]


In [28]:
import numpy as np
import os

HOUSING_PATH = '/cxldata/datasets/project/housing'
FILE = os.path.join(HOUSING_PATH, 'housing.csv')

def load_housing_dataset(file = FILE):
    return np.genfromtxt(file, dtype = {'names' : ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'), 'formats' : ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skip_header=1, filling_values = 99999999, unpack=False)

result_arr = load_housing_dataset()
print(len(result_arr))

print(result_arr)

20640
[(-122.23, 37.88, 41.,  880.,  129.,  322.,  126., 8.3252, 452600., b'NEAR BAY')
 (-122.22, 37.86, 21., 7099., 1106., 2401., 1138., 8.3014, 358500., b'NEAR BAY')
 (-122.24, 37.85, 52., 1467.,  190.,  496.,  177., 7.2574, 352100., b'NEAR BAY')
 ...
 (-121.22, 39.43, 17., 2254.,  485., 1007.,  433., 1.7   ,  92300., b'INLAND')
 (-121.32, 39.43, 18., 1860.,  409.,  741.,  349., 1.8672,  84700., b'INLAND')
 (-121.24, 39.37, 16., 2785.,  616., 1387.,  530., 2.3886,  89400., b'INLAND')]


In [35]:
import numpy as np

my_arr = np.array([ [0,1], [2,3] ])
print(my_arr)

my_arr.resize( (2, 3) )

print(my_arr)

[[0 1]
 [2 3]]
[[0 1 2]
 [3 0 0]]


In [53]:
import numpy as np

my_arr = np.array([[1,2,3,4], [5,6,7,8]])
print(my_arr)
my_arr.resize((3,4))
print(my_arr)

my_arr.resize((2,2))
print(my_arr)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [0 0 0 0]]
[[1 2]
 [3 4]]


In [49]:
my_arr = np.arange(6)
print(my_arr)

my_new_arr = my_arr.reshape(2,3)
print(my_new_arr)

my_arr = np.arange(9)
print(my_arr)

my_new_arr = my_arr.reshape(-1,3)
print(my_new_arr)

my_arr = np.arange(8)
print(my_arr)

my_arr.reshape(3,3)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7]


ValueError: cannot reshape array of size 8 into shape (3,3)

In [54]:
import numpy as np

my_first_arr = np.array([1,2,3,4,5,6,7,8])
my_new_arr = my_first_arr.reshape((2,4))
print(my_new_arr)
print(my_first_arr)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [55]:
my_second_arr = np.array([0,1,2,3,4,5,6,7,8])
my_updated_arr = my_second_arr.reshape((-1,3))
print(my_second_arr)
print(my_updated_arr)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [67]:
import numpy as np
arr = np.array([1, 10, 31, 2, 18, 9, 22])

print(arr[1])
part_arr = arr[2:5]
print(part_arr)
skip_arr = arr[1::2]
print(skip_arr)

10
[31  2 18]
[10  2  9]


In [69]:
import numpy as np

my_orig_arr = np.array([1, 15, 3, 9, 26, 7, 89, 12])
my_rev_arr = my_orig_arr[::-1]
print(my_rev_arr)

[12 89  7 26  9  3 15  1]


In [72]:
my_orig_arr2 = np.array([2, 9, 17, 13, 1, 4, 20, 57])
print(my_orig_arr2)
my_orig_arr2[2:5] = -6
print(my_orig_arr2)

[ 2  9 17 13  1  4 20 57]
[ 2  9 -6 -6 -6  4 20 57]


In [75]:
apple = np.array([1, 8, 23, 3, 18, 91, 7, 15])
apple_slice = apple[1:4]
print(apple_slice)
print(apple)

apple_slice[1] = 99999
print(apple_slice)
print(apple)
# Original (parent) array from which the slice was extracted also gets modified if the slice value is modified.

[ 8 23  3]
[ 1  8 23  3 18 91  7 15]
[    8 99999     3]
[    1     8 99999     3    18    91     7    15]


In [77]:
apple_slice_new = apple[2 : 5].copy()
apple_slice_new[1] = 222222
print(apple_slice_new)
print(apple)

[ 99999 222222     18]
[    1     8 99999     3    18    91     7    15]


In [ ]:
apple_slice_new = apple_slice[2:5].copy()